// <auto-generated />
using System;
using DCL.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCL.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260619122056_added lkps")]
    partial class addedlkps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DCL.Domain.Entities.Actor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodType")
                        .HasColumnType("TEXT");

                    b.Property<string>("BreastSize")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CupSize")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Facebook")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Height")
                        .HasColumnType("TEXT");

                    b.Property<string>("HipsSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instgram")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IsAdultsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Measurements")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Riddet")
                        .HasColumnType("TEXT");

                    b.Property<string>("Twiter")
                        .HasColumnType("TEXT");

                    b.Property<string>("WaistSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("actor", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.ActorTag", b =>
                {
                    b.Property<long>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActorId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ActorTags");
                });

            modelBuilder.Entity("DCL.Domain.Entities.AdultDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("AdultDetails");
                });

            modelBuilder.Entity("DCL.Domain.Entities.AgeRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_age_rating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MinAge = 0,
                            Name = "G"
                        },
                        new
                        {
                            Id = 2L,
                            MinAge = 10,
                            Name = "PG"
                        },
                        new
                        {
                            Id = 3L,
                            MinAge = 13,
                            Name = "PG-13"
                        },
                        new
                        {
                            Id = 4L,
                            MinAge = 17,
                            Name = "R"
                        },
                        new
                        {
                            Id = 5L,
                            MinAge = 18,
                            Name = "NC-17"
                        },
                        new
                        {
                            Id = 6L,
                            MinAge = 18,
                            Name = "XXX"
                        });
                });

            modelBuilder.Entity("DCL.Domain.Entities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("MediaId");

                    b.ToTable("lkp_Country", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.DownloadSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceTypeId");

                    b.ToTable("lkp_download_source", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.FileFormat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_file_format", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "MP4"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "MKV"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "AVI"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "MOV"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "WMV"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "FLAC"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "MP3"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "ISO"
                        });
                });

            modelBuilder.Entity("DCL.Domain.Entities.FrameRateMode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_frame_rate_mode", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "CFR"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "VFR"
                        });
                });

            modelBuilder.Entity("DCL.Domain.Entities.GameDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("GameDetails");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Gender", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("lkp_Gender", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Genre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_genre", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.ImageFileDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BitDepth")
                        .HasColumnType("REAL");

                    b.Property<string>("ColorSpace")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAlpha")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId")
                        .IsUnique();

                    b.ToTable("ImageFileDetails");
                });

            modelBuilder.Entity("DCL.Domain.Entities.IsAdult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("MediaId");

                    b.ToTable("lkp_IsAdult", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Label", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_label", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_language", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "ar",
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "ja",
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "de",
                            Name = "German"
                        });
                });

            modelBuilder.Entity("DCL.Domain.Entities.Lkp.Director", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_director", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Maker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_maker", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Media", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AgeRatingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IsAdultsId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgeRatingId");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaActor", b =>
                {
                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("media_actor", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileFormatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("StorageDeviceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileFormatId");

                    b.HasIndex("MediaId");

                    b.HasIndex("StorageDeviceId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaGenre", b =>
                {
                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MediaGenres");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaTag", b =>
                {
                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MediaTags");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaThumbnail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StorageDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("StorageDeviceId");

                    b.ToTable("MediaThumbnails");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StorageDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MediaId");

                    b.HasIndex("StorageDeviceId");

                    b.ToTable("MediaTranslations");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_media_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Movie"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Series"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Game"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Image"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Adult"
                        });
                });

            modelBuilder.Entity("DCL.Domain.Entities.MovieDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("MovieDetails");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MusicDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("MusicDetails");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Quality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolutionH")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResolutionW")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("lkp_quality", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "480p",
                            ResolutionH = 480,
                            ResolutionW = 854
                        },
                        new
                        {
                            Id = 2L,
                            Name = "720p",
                            ResolutionH = 720,
                            ResolutionW = 1280
                        },
                        new
                        {
                            Id = 3L,
                            Name = "1080p",
                            ResolutionH = 1080,
                            ResolutionW = 1920
                        },
                        new
                        {
                            Id = 4L,
                            Name = "1440p",
                            ResolutionH = 1440,
                            ResolutionW = 2560
                        },
                        new
                        {
                            Id = 5L,
                            Name = "4K",
                            ResolutionH = 2160,
                            ResolutionW = 3840
                        });
                });

            modelBuilder.Entity("DCL.Domain.Entities.ScanType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_scan_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Progressive"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Interlaced"
                        });
                });

            modelBuilder.Entity("DCL.Domain.Entities.SeriesDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("SeriesDetails");
                });

            modelBuilder.Entity("DCL.Domain.Entities.SourceType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_source_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Torrent"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Direct Download"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Usenet"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Physical"
                        });
                });

            modelBuilder.Entity("DCL.Domain.Entities.StorageDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FreeSpaceGb")
                        .HasColumnType("REAL");

                    b.Property<string>("MountPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalSpaceGb")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("lkp_storage_device", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_tag", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.VideoFileDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BitDepth")
                        .HasColumnType("REAL");

                    b.Property<double>("BitRate")
                        .HasColumnType("REAL");

                    b.Property<double>("BitsPerPixelFrame")
                        .HasColumnType("REAL");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<double>("FrameRate")
                        .HasColumnType("REAL");

                    b.Property<long?>("FrameRateModeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("QualityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceFrame")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScanTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FrameRateModeId");

                    b.HasIndex("MediaFileId")
                        .IsUnique();

                    b.HasIndex("QualityId");

                    b.HasIndex("ScanTypeId");

                    b.ToTable("VideoFileDetails");
                });

            modelBuilder.Entity("DCL.Domain.Entities.ActorTag", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Actor", "Actor")
                        .WithMany("Tags")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.Tag", "Tag")
                        .WithMany("ActorTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DCL.Domain.Entities.AdultDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithOne("AdultDetail")
                        .HasForeignKey("DCL.Domain.Entities.AdultDetail", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Country", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Actor", null)
                        .WithMany("Countries")
                        .HasForeignKey("ActorId");

                    b.HasOne("DCL.Domain.Entities.Media", null)
                        .WithMany("Countries")
                        .HasForeignKey("MediaId");
                });

            modelBuilder.Entity("DCL.Domain.Entities.DownloadSource", b =>
                {
                    b.HasOne("DCL.Domain.Entities.SourceType", "SourceType")
                        .WithMany()
                        .HasForeignKey("SourceTypeId");

                    b.Navigation("SourceType");
                });

            modelBuilder.Entity("DCL.Domain.Entities.GameDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithOne("GameDetail")
                        .HasForeignKey("DCL.Domain.Entities.GameDetail", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Gender", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Actor", null)
                        .WithMany("Genders")
                        .HasForeignKey("ActorId");
                });

            modelBuilder.Entity("DCL.Domain.Entities.ImageFileDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.MediaFile", "MediaFile")
                        .WithOne("ImageDetail")
                        .HasForeignKey("DCL.Domain.Entities.ImageFileDetail", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("DCL.Domain.Entities.IsAdult", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Actor", null)
                        .WithMany("IsAdults")
                        .HasForeignKey("ActorId");

                    b.HasOne("DCL.Domain.Entities.Media", null)
                        .WithMany("IsAdults")
                        .HasForeignKey("MediaId");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Media", b =>
                {
                    b.HasOne("DCL.Domain.Entities.AgeRating", "AgeRating")
                        .WithMany()
                        .HasForeignKey("AgeRatingId");

                    b.HasOne("DCL.Domain.Entities.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeRating");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaActor", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Actor", "Actor")
                        .WithMany("MediaActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithMany("Actors")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("DCL.Domain.Entities.FileFormat", "FileFormat")
                        .WithMany()
                        .HasForeignKey("FileFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithMany("Files")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.StorageDevice", "StorageDevice")
                        .WithMany()
                        .HasForeignKey("StorageDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileFormat");

                    b.Navigation("Media");

                    b.Navigation("StorageDevice");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaGenre", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Genre", "Genre")
                        .WithMany("MediaGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithMany("Genres")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaTag", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithMany("Tags")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.Tag", "Tag")
                        .WithMany("MediaTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaThumbnail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithMany("Thumbnails")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.StorageDevice", "StorageDevice")
                        .WithMany()
                        .HasForeignKey("StorageDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("StorageDevice");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaTranslation", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithMany("Translations")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.StorageDevice", "StorageDevice")
                        .WithMany()
                        .HasForeignKey("StorageDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Media");

                    b.Navigation("StorageDevice");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MovieDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithOne("MovieDetail")
                        .HasForeignKey("DCL.Domain.Entities.MovieDetail", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MusicDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithOne("MusicDetail")
                        .HasForeignKey("DCL.Domain.Entities.MusicDetail", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.SeriesDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithOne("SeriesDetail")
                        .HasForeignKey("DCL.Domain.Entities.SeriesDetail", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.VideoFileDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.FrameRateMode", "FrameRateMode")
                        .WithMany()
                        .HasForeignKey("FrameRateModeId");

                    b.HasOne("DCL.Domain.Entities.MediaFile", "MediaFile")
                        .WithOne("VideoDetail")
                        .HasForeignKey("DCL.Domain.Entities.VideoFileDetail", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.Quality", "Quality")
                        .WithMany()
                        .HasForeignKey("QualityId");

                    b.HasOne("DCL.Domain.Entities.ScanType", "ScanType")
                        .WithMany()
                        .HasForeignKey("ScanTypeId");

                    b.Navigation("FrameRateMode");

                    b.Navigation("MediaFile");

                    b.Navigation("Quality");

                    b.Navigation("ScanType");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Actor", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("Genders");

                    b.Navigation("IsAdults");

                    b.Navigation("MediaActors");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Genre", b =>
                {
                    b.Navigation("MediaGenres");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Media", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("AdultDetail");

                    b.Navigation("Countries");

                    b.Navigation("Files");

                    b.Navigation("GameDetail");

                    b.Navigation("Genres");

                    b.Navigation("IsAdults");

                    b.Navigation("MovieDetail");

                    b.Navigation("MusicDetail");

                    b.Navigation("SeriesDetail");

                    b.Navigation("Tags");

                    b.Navigation("Thumbnails");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaFile", b =>
                {
                    b.Navigation("ImageDetail");

                    b.Navigation("VideoDetail");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ActorTags");

                    b.Navigation("MediaTags");
                });
#pragma warning restore 612, 618
        }
    }
}
