// <auto-generated />
using System;
using DCL.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCL.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313153425_FixDetailTables")]
    partial class FixDetailTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DCL.Domain.Entities.AdultDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("AdultDetail");
                });

            modelBuilder.Entity("DCL.Domain.Entities.AgeRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_age_rating", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.DownloadSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceTypeId");

                    b.ToTable("lkp_download_source", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.FileFormat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_file_format", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.FrameRateMode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_frame_rate_mode", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.GameDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("GameDetail");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Genre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_genre", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Label", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_label", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_language", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Lkp.Actor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_actor", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Lkp.Director", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_director", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Maker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_maker", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Media", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AgeRatingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdultContent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgeRatingId");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BitDepth")
                        .HasColumnType("REAL");

                    b.Property<double>("BitRate")
                        .HasColumnType("REAL");

                    b.Property<double>("BitsPerPixelFrame")
                        .HasColumnType("REAL");

                    b.Property<long>("FileFormatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FrameRate")
                        .HasColumnType("REAL");

                    b.Property<long?>("FrameRateModeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("QualityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceFrame")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScanTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StorageDeviceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileFormatId");

                    b.HasIndex("FrameRateModeId");

                    b.HasIndex("MediaId");

                    b.HasIndex("QualityId");

                    b.HasIndex("ScanTypeId");

                    b.HasIndex("StorageDeviceId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaGenre", b =>
                {
                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MediaGenres");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaTag", b =>
                {
                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MediaTags");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaThumbnail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StorageDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("StorageDeviceId");

                    b.ToTable("MediaThumbnails");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StorageDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MediaId");

                    b.HasIndex("StorageDeviceId");

                    b.ToTable("MediaTranslations");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_media_type", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.MovieDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("MovieDetail");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MusicDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("MusicDetail");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Quality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolutionH")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResolutionW")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("lkp_quality", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.ScanType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_scan_type", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.SeriesDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("SeriesDetail");
                });

            modelBuilder.Entity("DCL.Domain.Entities.SourceType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_source_type", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.StorageDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FreeSpaceGb")
                        .HasColumnType("REAL");

                    b.Property<string>("MountPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalSpaceGb")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("lkp_storage_device", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lkp_tag", (string)null);
                });

            modelBuilder.Entity("DCL.Domain.Entities.AdultDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithOne("AdultDetail")
                        .HasForeignKey("DCL.Domain.Entities.AdultDetail", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.DownloadSource", b =>
                {
                    b.HasOne("DCL.Domain.Entities.SourceType", "SourceType")
                        .WithMany()
                        .HasForeignKey("SourceTypeId");

                    b.Navigation("SourceType");
                });

            modelBuilder.Entity("DCL.Domain.Entities.GameDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithOne("GameDetail")
                        .HasForeignKey("DCL.Domain.Entities.GameDetail", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Media", b =>
                {
                    b.HasOne("DCL.Domain.Entities.AgeRating", "AgeRating")
                        .WithMany()
                        .HasForeignKey("AgeRatingId");

                    b.HasOne("DCL.Domain.Entities.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeRating");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("DCL.Domain.Entities.FileFormat", "FileFormat")
                        .WithMany()
                        .HasForeignKey("FileFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.FrameRateMode", "FrameRateMode")
                        .WithMany()
                        .HasForeignKey("FrameRateModeId");

                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithMany("Files")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.Quality", "Quality")
                        .WithMany()
                        .HasForeignKey("QualityId");

                    b.HasOne("DCL.Domain.Entities.ScanType", "ScanType")
                        .WithMany()
                        .HasForeignKey("ScanTypeId");

                    b.HasOne("DCL.Domain.Entities.StorageDevice", "StorageDevice")
                        .WithMany()
                        .HasForeignKey("StorageDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileFormat");

                    b.Navigation("FrameRateMode");

                    b.Navigation("Media");

                    b.Navigation("Quality");

                    b.Navigation("ScanType");

                    b.Navigation("StorageDevice");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaGenre", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Genre", "Genre")
                        .WithMany("MediaGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithMany("Genres")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaTag", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithMany("Tags")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.Tag", "Tag")
                        .WithMany("MediaTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaThumbnail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithMany("Thumbnails")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.StorageDevice", "StorageDevice")
                        .WithMany()
                        .HasForeignKey("StorageDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("StorageDevice");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MediaTranslation", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithMany("Translations")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCL.Domain.Entities.StorageDevice", "StorageDevice")
                        .WithMany()
                        .HasForeignKey("StorageDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Media");

                    b.Navigation("StorageDevice");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MovieDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithOne("MovieDetail")
                        .HasForeignKey("DCL.Domain.Entities.MovieDetail", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.MusicDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithOne("MusicDetail")
                        .HasForeignKey("DCL.Domain.Entities.MusicDetail", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.SeriesDetail", b =>
                {
                    b.HasOne("DCL.Domain.Entities.Media", "Media")
                        .WithOne("SeriesDetail")
                        .HasForeignKey("DCL.Domain.Entities.SeriesDetail", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Genre", b =>
                {
                    b.Navigation("MediaGenres");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Media", b =>
                {
                    b.Navigation("AdultDetail");

                    b.Navigation("Files");

                    b.Navigation("GameDetail");

                    b.Navigation("Genres");

                    b.Navigation("MovieDetail");

                    b.Navigation("MusicDetail");

                    b.Navigation("SeriesDetail");

                    b.Navigation("Tags");

                    b.Navigation("Thumbnails");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("DCL.Domain.Entities.Tag", b =>
                {
                    b.Navigation("MediaTags");
                });
#pragma warning restore 612, 618
        }
    }
}
